// <auto-generated />
namespace OLX_Course.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addcity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addcity));
        
        string IMigrationMetadata.Id
        {
            get { return "202009080825423_Add city"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
